baseURL = 'https://sjx.wiki/'
languageCode = 'en'
title = 'Thor'
theme = 'dream'
[params]
zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "meta/background.jpg"
# backgroundImageDark = ""

author = "Thor"
# description = ""
avatar = "meta/background.jpg"
headerTitle = "Thor"
motto = "道阻且长，行则将至"

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

siteStartYear = 2025

# favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# imageZoomableInPost = true
# showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"